export const APPEND_NEW_ARTICLES = 'APPEND_NEW_ARTICLES';
export const INCREMENT_PAGE = 'INCREMENT_PAGE';
export const FETCH_SINGLE_ARTICLE = 'FETCH_SINGLE_ARTICLE';
export const REFRESH_ARTICLES = 'REFRESH_ARTICLES';
export const PIN_ARTICLE = 'PIN_ARTICLE';
